#!/usr/bin/env node
// Phase 1 — Scaffold target rsbuild SPA.
// Reads <sourceRoot>/.twsp/migration.json + audit.json.
// Materializes <targetRoot> from templates, runs npm install, runs shadcn init,
// runs verify build.
//
// Usage:
//   node scaffold-target.mjs [--source <path>]
//   node scaffold-target.mjs --self-test

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';
import {
  say, stop, parseArgs, selfTestGate, readMigration, readAudit, readState, writeState,
  readTemplate, writeFile, run, logSidecar, ensureDir, twspDir,
} from './_lib.mjs';

const SCRIPT = 'scaffold-target.mjs';
const args = parseArgs(process.argv.slice(2));
selfTestGate(args, SCRIPT);

function findSource() {
  if (args.flags.source) return resolve(args.flags.source);
  let d = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(d, '.twsp', 'migration.json'))) return d;
    const p = resolve(d, '..');
    if (p === d) break;
    d = p;
  }
  return null;
}

const sourceRoot = findSource();
if (!sourceRoot) stop('no migration.json found (run audit.mjs first)');
const m = readMigration(sourceRoot);
const audit = readAudit(sourceRoot);
const target = m.targetRoot;
const name = basename(target);

// Idempotency: if package.json already exists, treat as already scaffolded.
if (existsSync(join(target, 'package.json'))) {
  say(`scaffold: target already initialized at ${target}`);
  const state = readState(sourceRoot);
  state.step = 'scaffold';
  writeState(sourceRoot, state);
  process.exit(0);
}

ensureDir(target);
ensureDir(join(target, 'src'));

// ── Materialize templates ───────────────────────────────────────────
const subst = (s) => s.replaceAll('<NAME>', name);

writeFile(join(target, 'package.json'), subst(readTemplate('package.json.tmpl')));
writeFile(join(target, 'rsbuild.config.ts'), readTemplate('rsbuild.config.ts.tmpl'));
writeFile(join(target, 'postcss.config.js'), readTemplate('postcss.config.js.tmpl'));
writeFile(join(target, 'tsconfig.json'), readTemplate('tsconfig.json.tmpl'));
writeFile(join(target, 'eslint.config.js'), readTemplate('eslint.config.js.tmpl'));
writeFile(join(target, 'index.html'), subst(readTemplate('index.html.tmpl')));
writeFile(join(target, '.gitignore'), readTemplate('gitignore.tmpl'));

// Placeholder routes.gen.ts so main.tsx imports cleanly until Phase 5
writeFile(join(target, 'src', 'routes.gen.ts'), `import type { RouteObject } from 'react-router-dom';\nexport const routes: RouteObject[] = [\n  { path: '/', element: null },\n];\n`);

// Placeholder main.tsx (stripped of intl markers — Phase 5 rewrites)
const mainTpl = readTemplate('main.tsx.tmpl')
  .replace(/\/\/ <INTL_IMPORT>.*\n/g, '')
  .replace(/\{\/\* <INTL_PROVIDER_OPEN> \*\/\}\s*/g, '')
  .replace(/\s*\{\/\* <INTL_PROVIDER_CLOSE> \*\/\}/g, '');
writeFile(join(target, 'src', 'main.tsx'), mainTpl);

// Placeholder index.css — empty TW import; Phase 2a fills it
writeFile(join(target, 'src', 'index.css'), '@import "tailwindcss";\n');

// MIGRATION_NOTES placeholder
writeFile(join(target, 'MIGRATION_NOTES.md'), `# Migration notes\n\nGenerated by twsp-migration. TODOs and follow-ups are appended here as the port progresses.\n`);

// Initial git
const git1 = run('git', ['init', '-q'], { cwd: target });
if (git1.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, git1.stderr);
  stop('git init failed', log);
}
run('git', ['config', 'user.email', 'twsp@local'], { cwd: target });
run('git', ['config', 'user.name', 'twsp-migration'], { cwd: target });

// ── npm install ─────────────────────────────────────────────────────
say(`installing deps in ${target}…`);
const npmI = run('npm', ['install', '--silent', '--no-fund', '--no-audit'], { cwd: target });
if (npmI.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, npmI.stderr || npmI.stdout);
  stop('npm install failed', log);
}

// ── shadcn init ─────────────────────────────────────────────────────
say('shadcn init…');
const shInit = run('npx', ['--yes', 'shadcn@latest', 'init', '--yes', '--defaults', '--base-color', 'neutral', '--css-variables'], { cwd: target });
if (shInit.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, shInit.stderr || shInit.stdout);
  // Non-fatal — warn and continue. Phase 3/4 can re-init if needed.
  say(`shadcn init warning (continuing): ${log}`);
}

// ── verify ──────────────────────────────────────────────────────────
const tsc = run('npx', ['tsc', '--noEmit'], { cwd: target });
if (tsc.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, tsc.stderr || tsc.stdout);
  stop('scaffold tsc failed', log);
}
const build = run('npx', ['rsbuild', 'build'], { cwd: target });
if (build.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, build.stderr || build.stdout);
  stop('scaffold rsbuild build failed', log);
}

// ── State ───────────────────────────────────────────────────────────
const state = readState(sourceRoot);
state.step = 'scaffold';
writeState(sourceRoot, state);

say(`scaffold ok: ${target} (${name})`);
