#!/usr/bin/env node
// Phase 1 — Scaffold target rsbuild SPA, merging with any pre-existing target.
//
// Behavior:
//   - If target is absent or empty: full materialization from templates + npm install.
//   - If target has package.json: merge — only write files that don't already exist;
//     merge package.json deps (add missing template deps; never downgrade existing).
//   - Skips `git init` if target is already a git repo.
//   - Skips `shadcn init` if target already has components.json.
//   - Always runs npm install at the end.
//
// Usage:
//   node scaffold-target.mjs [--source <path>]
//   node scaffold-target.mjs --self-test

import { existsSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';
import {
  say, stop, parseArgs, selfTestGate, readMigration, readAudit, readState, writeState,
  readTemplate, writeFile, run, logSidecar, ensureDir, readPkg, writePkg,
} from './_lib.mjs';

const SCRIPT = 'scaffold-target.mjs';
const args = parseArgs(process.argv.slice(2));
selfTestGate(args, SCRIPT);

function findSource() {
  if (args.flags.source) return resolve(args.flags.source);
  let d = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(d, '.twsp', 'migration.json'))) return d;
    const p = resolve(d, '..');
    if (p === d) break;
    d = p;
  }
  return null;
}

const sourceRoot = findSource();
if (!sourceRoot) stop('no migration.json found (run audit.mjs first)');
const m = readMigration(sourceRoot);
const audit = readAudit(sourceRoot);
const target = m.targetRoot;
const name = basename(target);
const ta = audit?.targetAudit || {};

ensureDir(target);
ensureDir(join(target, 'src'));

// ── Helper: write file only if missing ──────────────────────────────
function writeIfAbsent(absPath, content) {
  if (existsSync(absPath)) return false;
  writeFile(absPath, content);
  return true;
}

const subst = (s) => s.replaceAll('<NAME>', name);

// ── Merge package.json (or write fresh) ─────────────────────────────
const tplPkg = JSON.parse(subst(readTemplate('package.json.tmpl')));
let pkg;
let mergedAdds = 0;
if (existsSync(join(target, 'package.json'))) {
  pkg = readPkg(target);
  if (!pkg) stop('target package.json is unreadable');
  pkg.dependencies = pkg.dependencies || {};
  pkg.devDependencies = pkg.devDependencies || {};
  pkg.scripts = pkg.scripts || {};
  // Add missing template deps. Do NOT downgrade or replace existing.
  for (const [k, v] of Object.entries(tplPkg.dependencies || {})) {
    if (!pkg.dependencies[k] && !pkg.devDependencies[k]) {
      pkg.dependencies[k] = v;
      mergedAdds++;
    }
  }
  for (const [k, v] of Object.entries(tplPkg.devDependencies || {})) {
    if (!pkg.dependencies[k] && !pkg.devDependencies[k]) {
      pkg.devDependencies[k] = v;
      mergedAdds++;
    }
  }
  // Add missing scripts. Don't overwrite custom ones.
  for (const [k, v] of Object.entries(tplPkg.scripts || {})) {
    if (!pkg.scripts[k]) pkg.scripts[k] = v;
  }
  writePkg(target, pkg);
  say(`merged package.json: added ${mergedAdds} dep(s)`);
} else {
  writeFile(join(target, 'package.json'), JSON.stringify(tplPkg, null, 2) + '\n');
  pkg = tplPkg;
  say(`wrote fresh package.json`);
}

// ── Config files: write only if absent ──────────────────────────────
const configs = [
  ['rsbuild.config.ts', 'rsbuild.config.ts.tmpl', false],
  ['postcss.config.js', 'postcss.config.js.tmpl', false],
  ['tsconfig.json', 'tsconfig.json.tmpl', false],
  ['eslint.config.js', 'eslint.config.js.tmpl', false],
  ['index.html', 'index.html.tmpl', true],
  ['.gitignore', 'gitignore.tmpl', false],
];
let configsWritten = 0;
for (const [filename, tmpl, doSubst] of configs) {
  const content = doSubst ? subst(readTemplate(tmpl)) : readTemplate(tmpl);
  if (writeIfAbsent(join(target, filename), content)) configsWritten++;
}

// Placeholder routes.gen.ts (only if absent)
writeIfAbsent(
  join(target, 'src', 'routes.gen.ts'),
  `import type { RouteObject } from 'react-router-dom';\nexport const routes: RouteObject[] = [\n  { path: '/', element: null },\n];\n`
);

// Placeholder main.tsx (only if absent — Phase 5 wires for real)
const mainTpl = readTemplate('main.tsx.tmpl')
  .replace(/\/\/ <INTL_IMPORT>.*\n/g, '')
  .replace(/\{\/\* <INTL_PROVIDER_OPEN> \*\/\}\s*/g, '')
  .replace(/\s*\{\/\* <INTL_PROVIDER_CLOSE> \*\/\}/g, '');
writeIfAbsent(join(target, 'src', 'main.tsx'), mainTpl);

// Placeholder index.css (only if absent — Phase 2a fills it)
writeIfAbsent(join(target, 'src', 'index.css'), '@import "tailwindcss";\n');

// MIGRATION_NOTES (always append-safe; create if missing)
writeIfAbsent(
  join(target, 'MIGRATION_NOTES.md'),
  `# Migration notes\n\nGenerated by twsp-migration. TODOs and follow-ups are appended here as the port progresses.\n`
);

say(`scaffold files: configs=${configsWritten} (existing preserved)`);

// ── Git init (skip if already a repo) ───────────────────────────────
if (!ta.hasGitDir && !existsSync(join(target, '.git'))) {
  const git1 = run('git', ['init', '-q'], { cwd: target });
  if (git1.code !== 0) {
    const log = logSidecar(sourceRoot, SCRIPT, git1.stderr);
    stop('git init failed', log);
  }
  run('git', ['config', 'user.email', 'twsp@local'], { cwd: target });
  run('git', ['config', 'user.name', 'twsp-migration'], { cwd: target });
  say('git init ok');
} else {
  say('git already initialized — skipping');
}

// ── npm install ─────────────────────────────────────────────────────
say(`installing deps in ${target}…`);
const npmI = run('npm', ['install', '--silent', '--no-fund', '--no-audit'], { cwd: target });
if (npmI.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, npmI.stderr || npmI.stdout);
  stop('npm install failed', log);
}

// ── shadcn init (skip if components.json already present) ───────────
if (!ta.hasComponentsJson && !existsSync(join(target, 'components.json'))) {
  say('shadcn init…');
  const shInit = run('npx', ['--yes', 'shadcn@latest', 'init', '--yes', '--defaults', '--base-color', 'neutral', '--css-variables'], { cwd: target });
  if (shInit.code !== 0) {
    const log = logSidecar(sourceRoot, SCRIPT, shInit.stderr || shInit.stdout);
    say(`shadcn init warning (continuing): ${log}`);
  }
} else {
  say('shadcn already initialized — skipping');
}

// ── verify ──────────────────────────────────────────────────────────
const tsc = run('npx', ['tsc', '--noEmit'], { cwd: target });
if (tsc.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, tsc.stderr || tsc.stdout);
  stop('scaffold tsc failed', log);
}
const build = run('npx', ['rsbuild', 'build'], { cwd: target });
if (build.code !== 0) {
  const log = logSidecar(sourceRoot, SCRIPT, build.stderr || build.stdout);
  stop('scaffold rsbuild build failed', log);
}

const state = readState(sourceRoot);
state.step = 'scaffold';
writeState(sourceRoot, state);

say(`scaffold ok: ${target} (${name}) mode=${ta.hasPackageJson ? 'merged' : 'fresh'}`);
